local Customize = {}

-- {{{ Customize documentation.
--
-- Customize table is a plugin name and true or false.  Using nvim_tree as the
-- example:
--   true - plug is loaded
--  false - plugin is NOT loaded.
--
-- This is a quick way to determine when a customization is interfering with
-- your expected behavior or two plugins are impacting with each other.

-- ------------------------------------------------------------------------- }}}

Customize = {
  plugins = {
    ["Comment.nvim"] = { enabled = false, defaults = true },
    ["LuaSnip"] = { enabled = true, defaults = true },
    ["alpha-nvim"] = { enabled = true, defaults = true },
    ["bufferline.nvim"] = { enabled = false, defaults = true },
    ["bullets.vim"] = { enabled = true, defaults = true },
    ["catppuccin"] = { enabled = true, defaults = true },
    ["clipboard-image.nvim"] = { enabled = true, defaults = true },
    ["crates.nvim"] = { enabled = true, defaults = true },
    ["dressing"] = { enabled = true, defaults = true },
    ["flit.nvim"] = { enabled = false, defaults = true },
    ["fzf.vim"] = { enabled = true, defaults = true },
    ["gem-browse"] = { enabled = true, defaults = true },
    ["gitsigns.nvim"] = { enabled = true, defaults = false },
    ["harpoon"] = { enabled = true, defaults = false},
    ["indent-blankline"] = { enabled = true, defaults = false },
    ["leap.nvim"] = { enabled = false, defaults = true },
    ["markdown-preview.nvim"] = { enabled = true },
    ["mason.nvim"] = { enabled = true, defaults = true },
    ["mason-nvim-dap.nvim"] = { enabled = true, },
    ["mini.ai"] = { enabled = true, defaults = true },
    ["mini.comment"] = { enabled = true, defaults = true },
    ["mini.indentscope"] = { enabled = false, defaults = true },
    ["mini.pairs"] = { enabled = false, defaults = true },
    ["mini.surround"] = { enabled = false, defaults = true },
    ["neo-tree.nvim"] = { enabled = true, defaults = false },
    ["neoconf.nvim"] = { enabled = true, defaults = true },
    ["neodev.nvim"] = { enabled = true, defaults = true },
    ["neoformat"] = { enabled = false, defaults = true },
    ["noice.nvim"] = { enabled = true, defaults = false },
    ["nui.nvim"] = { enabled = true, defaults = true },
    ["null-ls.nvim"] = { enabled = true, defaults = true },
    ["nvim-autopairs"] = { enabled = true, defaults = true },
    ["nvim-base16"] = { enabled = false, defaults = true },
    ["nvim-cmp"] = { enabled = true, defaults = false },
    ["nvim-colorizer.lua"] = { enabled = true, defaults = true },
    ["nvim-dap"] = { enabled = true, defaults = true },
    ["nvim-dap-go"] = { enabled = true, defaults = true },
    ["nvim-dap-python"] = { enabled = true, defaults = true },
    ["nvim-dap-ruby"] = { enabled = true, defaults = true },
    ["nvim-dap-ui"] = { enabled = true, defaults = false },
    ["nvim-dap-virtual-text"] = { enabled = true, defaults = true },
    ["nvim-lightbulb"] = { enabled = true, defaults = false },
    ["nvim-lspconfig"] = { enabled = true, defaults = true },
    ["nvim-navic"] = { enabled = true, defaults = true },
    ["nvim-notify"] = { enabled = true, defaults = false },
    ["nvim-spectre"] = { enabled = true, defaults = true },
    ["nvim-surround"] = { enabled = true, defaults = true },
    ["nvim-transparent"] = { enabled = false, defaults = true },
    ["nvim-tree"] = { enabled = false, defaults = true },
    ["nvim-treesitter"] = { enabled = true, defaults = true },
    ["nvim-ts-rainbow"] = { enabled = true, defaults = true },
    ["nvim-unimpaired"] = { enabled = true, defaults = true },
    ["nvim-web-devicons"] = { enabled = true, defaults = true },
    ["oil.nvim"] = { enabled = true, defaults = true },
    ["one-small-step-for-vimkind"] = { enabled = false },
    ["lualine.nvim"] = { enabled = true, defaults = false },
    ["plenary.nvim"] = { enabled = true, defaults = true },
    ["popup.nvim"] = { enabled = false, defaults = true },
    ["rainbow_csv"] = { enabled = true, defaults = true },
    ["rust-tools.nvim"] = { enabled = true, defaults = true },
    ["sxhkd-vim"] = { enabled = false, defaults = true },
    ["telescope.nvim"] = { enabled = true, defaults = true },
    ["telescope-dap.nvim"] = { enabled = true, defaults = true },
    ["telescope-fzf-native.nvim"] = { enabled = true, defaults = true },
    ["todo-comments.nvim"] = { enabled = true, defaults = true },
    ["toggleterm.nvim"] = { enabled = true, defaults = true },
    ["tokyonight.nvim"] = { enabled = true, defaults = false },
    ["trouble.nvim"] = { enabled = true, defaults = true },
    ["vim-bbye"] = { enabled = false, defaults = true },
    ["vim-bundle-abbreviate"] = { enabled = true, defaults = true },
    ["vim-bundle-fzf"] = { enabled = true, defaults = true },
    ["vim-bundle-plantuml"] = { enabled = true, defaults = true },
    ["vim-bundle-tmux-runner"] = { enabled = true, defaults = true },
    ["vim-bundle-vimtex"] = { enabled = true, defaults = true },
    ["vim-bundle-wiki.vim"] = { enabled = true, defaults = true },
    ["vim-bundler"] = { enabled = true, defaults = true },
    ["vim-commentary"] = { enabled = true, defaults = true },
    ["vim-easy-align"] = { enabled = true, defaults = true },
    ["vim-endwise"] = { enabled = true, defaults = true },
    ["vim-eunuch"] = { enabled = true, defaults = true },
    ["vim-dispatch"] = { enabled = true, defaults = true },
    ["vim-fugitive"] = { enabled = true, defaults = true },
    ["vim-illuminate"] = { enabled = true, defaults = true },
    ["vim-most-minimal-folds"] = { enabled = true, defaults = true },
    ["vim-projectionist"] = { enabled = true, defaults = true },
    ["vim-rails"] = { enabled = true, defaults = true },
    ["vim-rake"] = { enabled = true, defaults = true },
    ["vim-rbenv"] = { enabled = true, defaults = true },
    ["vim-repeat"] = { enabled = true, defaults = true },
    ["vim-speeddating"] = { enabled = true, defaults = true },
    ["vim-startuptime"] = { enabled = true, defaults = true },
    ["vim-surround"] = { enabled = false, defaults = true },
    ["vim-tmux-navigator"] = { enabled = true, defaults = true },
    ["vim-tmux-runner"] = { enabled = true, defaults = true },
    ["vim-unimpaired"] = { enabled = true, defaults = true },
    ["vim-visual-increment"] = { enabled = true, defaults = true },
    ["vimtex"] = { enabled = true, defaults = true },
    ["virtcolumn.nvim"] = { enabled = true, defaults = true },
    ["which-key.nvim"] = { enabled = true, defalts = true },
    ["wiki.vim"] = { enabled = true, defaults = true },
    ["wiki-ft.vim"] = { enabled = true, defaults = true },
    ["zen-mode.nvim"] = { enabled = true, defaults = true },
  },
}

return Customize
