Vapour.plugins.user = { {'Traap/nvim-base16.lua',            opt = false},
  {'Traap/vim-bundle-autocmd',         opt = false},
  {'Traap/vim-bundle-plantuml',        opt = false},
  {'Traap/vim-bundle-vimtex',          opt = false},
  {'Traap/vim-bundle-vimwiki',         opt = false},
  {'Traap/vim-ripgrep',                opt = false},
  {'christoomey/vim-tmux-navigator',   opt = false},
  {'christoomey/vim-tmux-runner',      opt = false},
  {'dkarter/bullets.vim',              opt = false},
  {'hrsh7th/cmp-cmdline',              opt = false},
  {'hrsh7th/cmp-path',                 opt = false},
  {'junegunn/vim-easy-align',          opt = false},
  {'lervag/vimtex',                    opt = false},
  {'lervag/wiki-ft.vim',               opt = false},
  {'lervag/wiki.vim',                  opt = false},
  {'mechatroner/rainbow_csv',          opt = false},
  {'norcalli/nvim-colorizer.lua',      opt = false},
  {'sbdchd/neoformat',                 opt = false},
  {'tpope/vim-commentary',             opt = false},
  {'tpope/vim-fugitive',               opt = false},
  {'tpope/vim-repeat',                 opt = false},
  {'tpope/vim-surround',               opt = false},
  {'tpope/vim-unimpaired',             opt = false},
  {'triglav/vim-visual-increment',     opt = false},
  {'vim-utils/vim-most-minimal-folds', opt = false},
  {'williamboman/nvim-lsp-installer',  opt = false},
  {'xiyaowong/nvim-transparent',       opt = false},
}
