return {
  -- {{{ dap icons

  dap = {
    Stopped             = " ",
    Breakpoint          = " ",
    BreakpointCondition = " ",
    BreakpointRejected  = " ",
    LogPoint            = ".>",
  },

  -- ----------------------------------------------------------------------- }}}
  -- {{{ diagnostics icons

  diagnostics = {
    BoldError = "",
    BoldHint = "",
    BoldInformation = "",
    BoldQuestion = "",
    BoldWarning = "",
    Debug = "",
    Error = " ",
    Hint = "",
    Information = "",
    Question = "",
    Trace = "✎",
    Warning = "",
  },

  -- ----------------------------------------------------------------------- }}}
  -- {{{ git icons

  git = {
    LineAdded = " ",
    LineModified = " ",
    LineRemoved = " ",
    FileDeleted = " ",
    FileIgnored = "◌",
    FileRenamed = " ",
    FileStaged = "S",
    FileUnmerged = "",
    FileUnstaged = "",
    FileUntracked = "U",
    Diff = " ",
    Repo = " ",
    Octoface = " ",
    Copilot = " ",
    Branch = "",
  },

  -- ----------------------------------------------------------------------- }}}
  -- {{{ kind icons

  kind = {
    Array = " ",
    Boolean = " ",
    Calc = " ",
    Class = " ",
    Codium = "",
    Color = " ",
    Constant = " ",
    Constructor = "",
    Control = "",
    Copilot = " ",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = " ",
    File = " ",
    Folder = "󰉋 ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = "",
    Method = " ",
    Module = "",
    Namespace = " ",
    Null = "󰟢 ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = "",
    Reference = " ",
    Snippet = " ",
    Spell = " ",
    String = " ",
    Struct = " ",
    TabNine = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = "",
    Value = " ",
    Variable = "β",
    Vsnip = " ",
    buffer = "",
    calc = " ",
    nvim_lsp = "",
    path = "",
    spell = " ",
    vsnip = " ",
  },

  -- ----------------------------------------------------------------------- }}}
  -- {{{ misc icons

  misc = {
    CircuitBoard = " ",
    Dots = " ",
    Package = " ",
    Robot = "󰚩 ",
    Smiley = " ",
    Squirrel = " ",
    Tag = " ",
    Watch = "",
  },

  -- ----------------------------------------------------------------------- }}}
  -- {{{ ui icons

  ui = {
    ArrowCircleDown = "",
    ArrowCircleLeft = "",
    ArrowCircleRight = "",
    ArrowCircleUp = "",
    BoldArrowDown = "",
    BoldArrowLeft = "",
    BoldArrowRight = "",
    BoldArrowUp = "",
    BoldClose = "",
    BoldDividerLeft = "",
    BoldDividerRight = "",
    BoldLineDashedMiddle = "┋",
    BoldLineLeft = "▎",
    BoldLineMiddle = "┃",
    BookMark = "",
    BoxChecked = " ",
    Bug = " ",
    Calendar = " ",
    Check = "",
    ChevronRight = "",
    ChevronShortDown = "",
    ChevronShortLeft = "",
    ChevronShortRight = "",
    ChevronShortUp = "",
    Circle = " ",
    Close = "󰅖",
    CloudDownload = " ",
    Code = "",
    Comment = "",
    Dashboard = "",
    DebugConsole = " ",
    DividerLeft = "",
    DividerRight = "",
    DoubleChevronRight = "»",
    Ellipsis = "",
    EmptyFolder = " ",
    EmptyFolderOpen = " ",
    Event = " ",
    File = " ",
    FileSymlink = "",
    Files = " ",
    FindFile = "󰂥",
    FindText = "",
    Fire = "",
    Folder = " ",
    FolderOpen = " ",
    FolderSymlink = " ",
    Forward = " ",
    Gear = " ",
    History = " ",
    Lazy = "⚡ ",
    Lightbulb = " ",
    LineLeft = "▏",
    LineMiddle = "│",
    List = " ",
    Lock = " ",
    Mason = " ",
    NewFile = " ",
    Note = " ",
    Package = " ",
    Pencil = "󰏫 ",
    Plus = " ",
    Quit = " ",
    Project = " ",
    Scopes = "",
    Search = " ",
    SignIn = " ",
    SignOut = " ",
    Stacks = "",
    Tab = "󰌒 ",
    Table = " ",
    Target = "󰀘 ",
    Telescope = " ",
    Text = " ",
    Tree = "",
    Triangle = "󰐊",
    TriangleShortArrowDown = "",
    TriangleShortArrowLeft = "",
    TriangleShortArrowRight = "",
    TriangleShortArrowUp = "",
    Watches = "󰂥",
  },

  -- ----------------------------------------------------------------------- }}}
}
