local Customize = {}
-- {{{ Customize documentation.
--
--  enabled:
--      true - plug is loaded
--     false - plugin is NOT loaded.
--
-- ------------------------------------------------------------------------- }}}
-- {{{ Customzie table

Customize                          = {
  plugins                          = {
    ["LuaSnip"]                    = { enabled = true  },
    ["bullets.vim"]                = { enabled = true  },
    ["catppuccin"]                 = { enabled = true  },
    ["clipboard-image.nvim"]       = { enabled = true  },
    ["crates.nvim"]                = { enabled = true  },
    ["conform.nvim"]               = { enabled = true  },
    ["dashboard-nvim"]             = { enabled = true  },
    ["dressing.nvim"]              = { enabled = true  },
    ["flit.nvim"]                  = { enabled = true  },
    ["friendly-snippets"]          = { enabled = true  },
    ["fzf.vim"]                    = { enabled = true  },
    ["gem-browse"]                 = { enabled = true  },
    ["gitsigns.nvim"]              = { enabled = true  },
    ["harpoon"]                    = { enabled = true  },
    ["indent-blankline"]           = { enabled = true  },
    ["leap.nvim"]                  = { enabled = true  },
    ["lualine.nvim"]               = { enabled = true  },
    ["markdown-preview.nvim"]      = { enabled = true  },
    ["mason-nvim-dap.nvim"]        = { enabled = true  },
    ["mason.nvim"]                 = { enabled = true  },
    ["neo-tree.nvim"]              = { enabled = true  },
    ["noice.nvim"]                 = { enabled = true  },
    ["none-ls.nvim"]               = { enabled = true  },
    ["nui.nvim"]                   = { enabled = true  },
    ["nvim-autopairs"]             = { enabled = true  },
    ["nvim-cmp"]                   = { enabled = true  },
    ["nvim-colorizer.lua"]         = { enabled = true  },
    ["nvim-dap"]                   = { enabled = true  },
    ["nvim-dap-go"]                = { enabled = true  },
    ["nvim-dap-python"]            = { enabled = true  },
    ["nvim-dap-ruby"]              = { enabled = true  },
    ["nvim-dap-ui"]                = { enabled = true  },
    ["nvim-dap-virtual-text"]      = { enabled = true  },
    ["nvim-lightbulb"]             = { enabled = true  },
    ["nvim-lspconfig"]             = { enabled = true  },
    ["nvim-navic"]                 = { enabled = true  },
    ["nvim-notify"]                = { enabled = true  },
    ["nvim-spectre"]               = { enabled = true  },
    ["nvim-surround"]              = { enabled = true  },
    ["nvim-toggler"]               = { enabled = true  },
    ["nvim-transparent"]           = { enabled = true  },
    ["nvim-treesitter"]            = { enabled = true  },
    ["nvim-treesitter-context"]    = { enabled = false },
    ["nvim-ts-rainbow"]            = { enabled = true  },
    ["nvim-unimpaired"]            = { enabled = true  },
    ["nvim-web-devicons"]          = { enabled = true  },
    ["oil.nvim"]                   = { enabled = true  },
    ["one-small-step-for-vimkind"] = { enabled = false },
    ["plantuml-syntax"]            = { enabled = true  },
    ["plenary.nvim"]               = { enabled = true  },
    ["popup.nvim"]                 = { enabled = true },
    ["rainbow_csv"]                = { enabled = true  },
    ["rust-tools.nvim"]            = { enabled = true  },
    ["sxhkd-vim"]                  = { enabled = false },
    ["telescope-dap.nvim"]         = { enabled = true  },
    ["telescope-fzf-native.nvim"]  = { enabled = true  },
    ["telescope.nvim"]             = { enabled = true  },
    ["todo-comments.nvim"]         = { enabled = true  },
    ["toggleterm.nvim"]            = { enabled = true  },
    ["tokyonight.nvim"]            = { enabled = true  },
    ["trouble.nvim"]               = { enabled = true  },
    ["vim-bbye"]                   = { enabled = false },
    ["vim-bundle-abbreviate"]      = { enabled = true  },
    ["vim-bundle-fzf"]             = { enabled = true  },
    ["vim-bundle-plantuml"]        = { enabled = true  },
    ["vim-bundle-tmux-runner"]     = { enabled = true  },
    ["vim-bundle-vimtex"]          = { enabled = true  },
    ["vim-bundle-wiki.vim"]        = { enabled = true  },
    ["vim-bundler"]                = { enabled = true  },
    ["vim-commentary"]             = { enabled = true  },
    ["vim-dispatch"]               = { enabled = true  },
    ["vim-easy-align"]             = { enabled = true  },
    ["vim-endwise"]                = { enabled = true  },
    ["vim-eunuch"]                 = { enabled = true  },
    ["vim-fugitive"]               = { enabled = true  },
    ["vim-most-minimal-folds"]     = { enabled = true  },
    ["vim-projectionist"]          = { enabled = true  },
    ["vim-rails"]                  = { enabled = true  },
    ["vim-rake"]                   = { enabled = true  },
    ["vim-rbenv"]                  = { enabled = true  },
    ["vim-repeat"]                 = { enabled = true  },
    ["vim-speeddating"]            = { enabled = true  },
    ["vim-startuptime"]            = { enabled = true  },
    ["vim-surround"]               = { enabled = false },
    ["vim-tmux-navigator"]         = { enabled = true  },
    ["vim-tmux-runner"]            = { enabled = true  },
    ["vim-unimpaired"]             = { enabled = true  },
    ["vim-visual-increment"]       = { enabled = true  },
    ["vimtex"]                     = { enabled = true  },
    ["virtcolumn.nvim"]            = { enabled = true  },
    ["which-key.nvim"]             = { enabled = true  },
    ["wiki-ft.vim"]                = { enabled = true  },
    ["wiki.vim"]                   = { enabled = true  },
    ["zen-mode.nvim"]              = { enabled = true  },
  },
}

-- ------------------------------------------------------------------------- }}}
return Customize
